version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: store
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb+srv://poojan4ps:Poojan@123@cloudproject1.h5ru20b.mongodb.net/test"
      secretOrKey: "36a14fe2-c485-45b0-b1b5-e28907fe389a"
    ports:
      - "5000:5000"




  